// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqcod8TGGCqncJha9ZtsqhcotjwQcmHCA',
    appId: '1:21128283873:web:0171a40447070ef244d9a',
    messagingSenderId: '21128283873',
    projectId: 'fatoramer',
    authDomain: 'fatoramer.firebaseapp.com',
    storageBucket: 'fatoramer.appspot.com',
    measurementId: 'G-TQK1D17GJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_3r5Xy1bU7IP6JmpkK_2GFFwPIb2d3Qc',
    appId: '1:21128283873:android:16e0295f9ba6ece644d9a0',
    messagingSenderId: '21128283873',
    projectId: 'fatoramer',
    storageBucket: 'fatoramer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiNWLXOr-5xOmsQK_jeuYRONLpPZwwdOI',
    appId: '1:1075958195445:ios:488b8ee43ef2e682a811bc',
    messagingSenderId: '21128283873',
    projectId: 'fatoramer',
    storageBucket: 'fatoramechantapp.appspot.com',
    iosBundleId: 'com.example.fatoraMerchantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiNWLXOr-5xOmsQK_jeuYRONLpPZwwdOI',
    appId: '1:1075958195445:ios:b61585170f2fea85a811bc',
    messagingSenderId: '21128283873',
    projectId: 'fatoramer',
    storageBucket: 'fatoramechantapp.appspot.com',
    iosBundleId: 'com.example.fatoraMerchantApp.RunnerTests',
  );
}
